name: Confluence Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: backend
        run: npm install

      - name: Generate diff
        working-directory: backend
        run: node scripts/generateDiff.js

      - name: Generate context
        working-directory: backend
        run: node scripts/aiContextFromDiff.js

      - name: Generate markdown
        working-directory: backend
        run: node scripts/aiMarkdownFromContext.js
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Publish to Confluence
        working-directory: backend
        run: node scripts/generateConfluenceDocs.js
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_SPACE_KEY: VKYC
          CONFLUENCE_PARENT_PAGE_ID: 2195457
